#!/bin/bash
[ $# -eq 2 ] || { echo "Usage: $0 <token> <secret>"; exit 1; }
token=$1
secret=$2
res=("--resource" "/users/__SELF__/shops")
script_dir=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd -P)
VIRTUAL_ENV="$script_dir/venv" PATH="$script_dir/venv/bin:$PATH" "$script_dir/venv/bin/python3" "$script_dir/get_oauth_etsy.py" \
	--client-token 'vvk0635ljecl7qvlat8h6lpo'	\
	--client-secret 'a3fdz078a0'	\
	--user-token "$token"	\
	--user-secret "$secret"	\
	--method get	\
	"${res[@]}" | json-pretty | egrep 'shop_id|shop_name'

#--authorize
