#!/bin/bash
[ -n "$2" ] || { printf "%s\n%s\n" "Usage: $0 <url> <data>" "$0"' /v2/listings/472667359/images '\''{"listing_id": "472667359", "rank:": "1", "overwrite": "1", "base64:image": "'\''`base64 -w 0 my.img`'\''"}'\'; exit 1; }
resource=$1
data=$2
script_dir=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd -P)
python3 "$script_dir/get_oauth_etsy.py" \
	--client-token "$VELA_CLIENT_TOKEN" \
	--client-secret "$VELA_CLIENT_SECRET" \
	--user-token "$USER_TOKEN_GEORGY" \
	--user-secret "$USER_SECRET_GEORGY" \
	--method post	\
	--resource "$resource"	\
	--data "$data"

#--authorize
