#!/bin/bash
[ -n "$2" ] || { printf "%s\n%s\n" "Usage: $0 <url> <data>" "$0 /v2/listings/288945115 '{\"description\": \"Cau\", \"last_modified_tsz\": \"`date +%s`\", \"state\": \"draft\"}'"; exit 1; }
resource=$1
data=$2
script_dir=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd -P)
python3 "$script_dir/get_oauth_etsy.py" \
	--client-token "$VELA_CLIENT_TOKEN" \
	--client-secret "$VELA_CLIENT_SECRET" \
	--user-token "$USER_TOKEN_KEYSER" \
	--user-secret "$USER_SECRET_KEYSER" \
	--method put	\
	--resource "$resource"	\
	--data "$data"

#--authorize
