export default {
  APPLICATION_WILL_MOUNT: 'APPLICATION_WILL_MOUNT',
  ROUTER_BOOTSTRAPPED: 'ROUTER_BOOTSTRAPPED',

  LOGIN_SUBMIT: 'LOGIN_SUBMIT',

  LOGIN_IN_PROGRESS: 'LOGIN_IN_PROGRESS',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_ERROR: 'LOGIN_ERROR',

  CHANGE_PATH: 'CHANGE_PATH'
};
