#!/bin/bash

set -e

script_dir=$(dirname "$(readlink -e "${BASH_SOURCE[0]}")")
cd "$script_dir"

if [ -z "$1" ]; then
	echo "Syntax: $0 <db_name>

Example: $0 db1"
	exit
fi

# Read config
. ./test.shopify.$1.cfg

# Start selenium if needed
ps -ef | grep 'java[ ].*selenium-server' >/dev/null || {
	selenium &> /dev/null&
	sleep 3
}

# Run shishito
"$script_dir/../bin/shi" --test_directory tests_e2e --test test_shopify_upload.py
