# Generated by api_requests2test_data.py

api_products_unpacked1 = [{
    'offerings': [{
        'is_enabled': 1,
        'price': 23.5,
        'quantity': 50
    }],
    'property_values': [{
        'property_id': 502,
        'property_name': 'Fabric',
        'scale_id': None,
        'value': 'wool',
        'value_id': None
    }, {
        'property_id': 200,
        'property_name': 'Color (primary)',
        'scale_id': None,
        'value': 'Black',
        'value_id': 1
    }],
    'sku': '550'
}, {
    'offerings': [{
        'is_enabled': 1,
        'price': 200,
        'quantity': 50
    }],
    'property_values': [{
        'property_id': 502,
        'property_name': 'Fabric',
        'scale_id': None,
        'value': 'wool',
        'value_id': None
    }, {
        'property_id': 200,
        'property_name': 'Color (primary)',
        'scale_id': None,
        'value': 'White',
        'value_id': 10
    }],
    'sku': '550'
}, {
    'offerings': [{
        'is_enabled': 1,
        'price': 250,
        'quantity': 50
    }],
    'property_values': [{
        'property_id': 502,
        'property_name': 'Fabric',
        'scale_id': None,
        'value': 'cotton',
        'value_id': None
    }, {
        'property_id': 200,
        'property_name': 'Color (primary)',
        'scale_id': None,
        'value': 'Black',
        'value_id': 1
    }],
    'sku': '550'
}, {
    'offerings': [{
        'is_enabled': 1,
        'price': 300,
        'quantity': 50
    }],
    'property_values': [{
        'property_id': 502,
        'property_name': 'Fabric',
        'scale_id': None,
        'value': 'cotton',
        'value_id': None
    }, {
        'property_id': 200,
        'property_name': 'Color (primary)',
        'scale_id': None,
        'value': 'White',
        'value_id': 10
    }],
    'sku': '550'
}]

api_products_unpacked2 = [{
    'offerings': [{
        'is_enabled': 1,
        'price': 23.5,
        'quantity': 11
    }],
    'property_values': [{
        'property_id': 502,
        'property_name': 'Fabric',
        'scale_id': None,
        'value': 'wool',
        'value_id': None
    }, {
        'property_id': 200,
        'property_name': 'Color (primary)',
        'scale_id': None,
        'value': 'Black',
        'value_id': 1
    }],
    'sku': '111'
}, {
    'offerings': [{
        'is_enabled': 1,
        'price': 200,
        'quantity': 11
    }],
    'property_values': [{
        'property_id': 502,
        'property_name': 'Fabric',
        'scale_id': None,
        'value': 'wool',
        'value_id': None
    }, {
        'property_id': 200,
        'property_name': 'Color (primary)',
        'scale_id': None,
        'value': 'White',
        'value_id': 10
    }],
    'sku': '111'
}, {
    'offerings': [{
        'is_enabled': 1,
        'price': 250,
        'quantity': 11
    }],
    'property_values': [{
        'property_id': 502,
        'property_name': 'Fabric',
        'scale_id': None,
        'value': 'cotton',
        'value_id': None
    }, {
        'property_id': 200,
        'property_name': 'Color (primary)',
        'scale_id': None,
        'value': 'Black',
        'value_id': 1
    }],
    'sku': '111'
}, {
    'offerings': [{
        'is_enabled': 1,
        'price': 300,
        'quantity': 11
    }],
    'property_values': [{
        'property_id': 502,
        'property_name': 'Fabric',
        'scale_id': None,
        'value': 'cotton',
        'value_id': None
    }, {
        'property_id': 200,
        'property_name': 'Color (primary)',
        'scale_id': None,
        'value': 'White',
        'value_id': 10
    }],
    'sku': '111'
}]

api_products_unpacked3 = [{
    'offerings': [{
        'is_enabled': 1,
        'price': 23.5,
        'quantity': 45
    }],
    'property_values': [{
        'property_id': 502,
        'property_name': 'Fabric',
        'scale_id': None,
        'value': 'wool',
        'value_id': None
    }, {
        'property_id': 200,
        'property_name': 'Color (primary)',
        'scale_id': None,
        'value': 'Black',
        'value_id': 1
    }],
    'sku': '222'
}, {
    'offerings': [{
        'is_enabled': 1,
        'price': 200,
        'quantity': 45
    }],
    'property_values': [{
        'property_id': 502,
        'property_name': 'Fabric',
        'scale_id': None,
        'value': 'wool',
        'value_id': None
    }, {
        'property_id': 200,
        'property_name': 'Color (primary)',
        'scale_id': None,
        'value': 'White',
        'value_id': 10
    }],
    'sku': '222'
}, {
    'offerings': [{
        'is_enabled': 1,
        'price': 250,
        'quantity': 45
    }],
    'property_values': [{
        'property_id': 502,
        'property_name': 'Fabric',
        'scale_id': None,
        'value': 'cotton',
        'value_id': None
    }, {
        'property_id': 200,
        'property_name': 'Color (primary)',
        'scale_id': None,
        'value': 'Black',
        'value_id': 1
    }],
    'sku': '222'
}, {
    'offerings': [{
        'is_enabled': 1,
        'price': 300,
        'quantity': 45
    }],
    'property_values': [{
        'property_id': 502,
        'property_name': 'Fabric',
        'scale_id': None,
        'value': 'cotton',
        'value_id': None
    }, {
        'property_id': 200,
        'property_name': 'Color (primary)',
        'scale_id': None,
        'value': 'White',
        'value_id': 10
    }],
    'sku': '222'
}]

expected_api_calls = [{
    'PUT': '/v2/listings/100001',
    'body': {
        'listing_id': 100001,
        'state': 'active',
        'taxonomy_id': 967
    }
}, {
    'PUT': '/v2/listings/100001/inventory?price_on_property=502,200&quantity_on_property=&sku_on_property=',
    'body': {
        '_products_unpacked': api_products_unpacked1,
        'listing_id': 100001
    }
}, {
    'PUT': '/v2/listings/100002',
    'body': {
        'listing_id': 100002,
        'state': 'active',
        'taxonomy_id': 967
    }
}, {
    'PUT': '/v2/listings/100002/inventory?price_on_property=502,200&quantity_on_property=&sku_on_property=',
    'body': {
        '_products_unpacked': api_products_unpacked2,
        'listing_id': 100002
    }
}, {
    'PUT': '/v2/listings/100003',
    'body': {
        'listing_id': 100003,
        'state': 'active',
        'taxonomy_id': 967
    }
}, {
    'PUT': '/v2/listings/100003/inventory?price_on_property=502,200&quantity_on_property=&sku_on_property=',
    'body': {
        '_products_unpacked': api_products_unpacked3,
        'listing_id': 100003
    }
}]