# Generated by api_requests2test_data.py

api_products_unpacked1 = [{
    'offerings': [{
        'is_enabled': 1,
        'price': 33.33,
        'quantity': 33
    }],
    'property_values': [{
        'property_id': 200,
        'property_name': 'Color (primary)',
        'scale_id': None,
        'value': 'Beige',
        'value_id': 1213
    }, {
        'property_id': 52047899002,
        'property_name': 'Color (secondary)',
        'scale_id': None,
        'value': 'Blue',
        'value_id': 2
    }],
    'sku': '550'
}, {
    'offerings': [{
        'is_enabled': 1,
        'price': 333.33,
        'quantity': 33
    }],
    'property_values': [{
        'property_id': 200,
        'property_name': 'Color (primary)',
        'scale_id': None,
        'value': 'Beige',
        'value_id': 1213
    }, {
        'property_id': 52047899002,
        'property_name': 'Color (secondary)',
        'scale_id': None,
        'value': 'Levande',
        'value_id': None
    }],
    'sku': '550'
}, {
    'offerings': [{
        'is_enabled': 1,
        'price': 33.33,
        'quantity': 33
    }],
    'property_values': [{
        'property_id': 200,
        'property_name': 'Color (primary)',
        'scale_id': None,
        'value': 'Black',
        'value_id': 1
    }, {
        'property_id': 52047899002,
        'property_name': 'Color (secondary)',
        'scale_id': None,
        'value': 'Blue',
        'value_id': 2
    }],
    'sku': '550'
}, {
    'offerings': [{
        'is_enabled': 1,
        'price': 333.33,
        'quantity': 33
    }],
    'property_values': [{
        'property_id': 200,
        'property_name': 'Color (primary)',
        'scale_id': None,
        'value': 'Black',
        'value_id': 1
    }, {
        'property_id': 52047899002,
        'property_name': 'Color (secondary)',
        'scale_id': None,
        'value': 'Levande',
        'value_id': None
    }],
    'sku': '550'
}, {
    'offerings': [{
        'is_enabled': 1,
        'price': 33.33,
        'quantity': 33
    }],
    'property_values': [{
        'property_id': 200,
        'property_name': 'Color (primary)',
        'scale_id': None,
        'value': 'Blue',
        'value_id': 2
    }, {
        'property_id': 52047899002,
        'property_name': 'Color (secondary)',
        'scale_id': None,
        'value': 'Blue',
        'value_id': 2
    }],
    'sku': '550'
}, {
    'offerings': [{
        'is_enabled': 1,
        'price': 333.33,
        'quantity': 33
    }],
    'property_values': [{
        'property_id': 200,
        'property_name': 'Color (primary)',
        'scale_id': None,
        'value': 'Blue',
        'value_id': 2
    }, {
        'property_id': 52047899002,
        'property_name': 'Color (secondary)',
        'scale_id': None,
        'value': 'Levande',
        'value_id': None
    }],
    'sku': '550'
}, {
    'offerings': [{
        'is_enabled': 1,
        'price': 33.33,
        'quantity': 33
    }],
    'property_values': [{
        'property_id': 200,
        'property_name': 'Color (primary)',
        'scale_id': None,
        'value': 'Bronze',
        'value_id': 1216
    }, {
        'property_id': 52047899002,
        'property_name': 'Color (secondary)',
        'scale_id': None,
        'value': 'Blue',
        'value_id': 2
    }],
    'sku': '550'
}, {
    'offerings': [{
        'is_enabled': 1,
        'price': 333.33,
        'quantity': 33
    }],
    'property_values': [{
        'property_id': 200,
        'property_name': 'Color (primary)',
        'scale_id': None,
        'value': 'Bronze',
        'value_id': 1216
    }, {
        'property_id': 52047899002,
        'property_name': 'Color (secondary)',
        'scale_id': None,
        'value': 'Levande',
        'value_id': None
    }],
    'sku': '550'
}, {
    'offerings': [{
        'is_enabled': 1,
        'price': 33.33,
        'quantity': 33
    }],
    'property_values': [{
        'property_id': 200,
        'property_name': 'Color (primary)',
        'scale_id': None,
        'value': 'Brown',
        'value_id': 3
    }, {
        'property_id': 52047899002,
        'property_name': 'Color (secondary)',
        'scale_id': None,
        'value': 'Blue',
        'value_id': 2
    }],
    'sku': '550'
}, {
    'offerings': [{
        'is_enabled': 1,
        'price': 333.33,
        'quantity': 33
    }],
    'property_values': [{
        'property_id': 200,
        'property_name': 'Color (primary)',
        'scale_id': None,
        'value': 'Brown',
        'value_id': 3
    }, {
        'property_id': 52047899002,
        'property_name': 'Color (secondary)',
        'scale_id': None,
        'value': 'Levande',
        'value_id': None
    }],
    'sku': '550'
}, {
    'offerings': [{
        'is_enabled': 1,
        'price': 33.33,
        'quantity': 33
    }],
    'property_values': [{
        'property_id': 200,
        'property_name': 'Color (primary)',
        'scale_id': None,
        'value': 'Clear',
        'value_id': 1219
    }, {
        'property_id': 52047899002,
        'property_name': 'Color (secondary)',
        'scale_id': None,
        'value': 'Blue',
        'value_id': 2
    }],
    'sku': '550'
}, {
    'offerings': [{
        'is_enabled': 1,
        'price': 333.33,
        'quantity': 33
    }],
    'property_values': [{
        'property_id': 200,
        'property_name': 'Color (primary)',
        'scale_id': None,
        'value': 'Clear',
        'value_id': 1219
    }, {
        'property_id': 52047899002,
        'property_name': 'Color (secondary)',
        'scale_id': None,
        'value': 'Levande',
        'value_id': None
    }],
    'sku': '550'
}, {
    'offerings': [{
        'is_enabled': 1,
        'price': 33.33,
        'quantity': 33
    }],
    'property_values': [{
        'property_id': 200,
        'property_name': 'Color (primary)',
        'scale_id': None,
        'value': 'Copper',
        'value_id': 1218
    }, {
        'property_id': 52047899002,
        'property_name': 'Color (secondary)',
        'scale_id': None,
        'value': 'Blue',
        'value_id': 2
    }],
    'sku': '550'
}, {
    'offerings': [{
        'is_enabled': 1,
        'price': 333.33,
        'quantity': 33
    }],
    'property_values': [{
        'property_id': 200,
        'property_name': 'Color (primary)',
        'scale_id': None,
        'value': 'Copper',
        'value_id': 1218
    }, {
        'property_id': 52047899002,
        'property_name': 'Color (secondary)',
        'scale_id': None,
        'value': 'Levande',
        'value_id': None
    }],
    'sku': '550'
}, {
    'offerings': [{
        'is_enabled': 1,
        'price': 33.33,
        'quantity': 33
    }],
    'property_values': [{
        'property_id': 200,
        'property_name': 'Color (primary)',
        'scale_id': None,
        'value': 'Gold',
        'value_id': 1214
    }, {
        'property_id': 52047899002,
        'property_name': 'Color (secondary)',
        'scale_id': None,
        'value': 'Blue',
        'value_id': 2
    }],
    'sku': '550'
}, {
    'offerings': [{
        'is_enabled': 1,
        'price': 333.33,
        'quantity': 33
    }],
    'property_values': [{
        'property_id': 200,
        'property_name': 'Color (primary)',
        'scale_id': None,
        'value': 'Gold',
        'value_id': 1214
    }, {
        'property_id': 52047899002,
        'property_name': 'Color (secondary)',
        'scale_id': None,
        'value': 'Levande',
        'value_id': None
    }],
    'sku': '550'
}, {
    'offerings': [{
        'is_enabled': 1,
        'price': 33.33,
        'quantity': 33
    }],
    'property_values': [{
        'property_id': 200,
        'property_name': 'Color (primary)',
        'scale_id': None,
        'value': 'Gray',
        'value_id': 5
    }, {
        'property_id': 52047899002,
        'property_name': 'Color (secondary)',
        'scale_id': None,
        'value': 'Blue',
        'value_id': 2
    }],
    'sku': '550'
}, {
    'offerings': [{
        'is_enabled': 1,
        'price': 333.33,
        'quantity': 33
    }],
    'property_values': [{
        'property_id': 200,
        'property_name': 'Color (primary)',
        'scale_id': None,
        'value': 'Gray',
        'value_id': 5
    }, {
        'property_id': 52047899002,
        'property_name': 'Color (secondary)',
        'scale_id': None,
        'value': 'Levande',
        'value_id': None
    }],
    'sku': '550'
}, {
    'offerings': [{
        'is_enabled': 1,
        'price': 33.33,
        'quantity': 33
    }],
    'property_values': [{
        'property_id': 200,
        'property_name': 'Color (primary)',
        'scale_id': None,
        'value': 'Green',
        'value_id': 4
    }, {
        'property_id': 52047899002,
        'property_name': 'Color (secondary)',
        'scale_id': None,
        'value': 'Blue',
        'value_id': 2
    }],
    'sku': '550'
}, {
    'offerings': [{
        'is_enabled': 1,
        'price': 333.33,
        'quantity': 33
    }],
    'property_values': [{
        'property_id': 200,
        'property_name': 'Color (primary)',
        'scale_id': None,
        'value': 'Green',
        'value_id': 4
    }, {
        'property_id': 52047899002,
        'property_name': 'Color (secondary)',
        'scale_id': None,
        'value': 'Levande',
        'value_id': None
    }],
    'sku': '550'
}, {
    'offerings': [{
        'is_enabled': 1,
        'price': 33.33,
        'quantity': 33
    }],
    'property_values': [{
        'property_id': 200,
        'property_name': 'Color (primary)',
        'scale_id': None,
        'value': 'Orange',
        'value_id': 6
    }, {
        'property_id': 52047899002,
        'property_name': 'Color (secondary)',
        'scale_id': None,
        'value': 'Blue',
        'value_id': 2
    }],
    'sku': '550'
}, {
    'offerings': [{
        'is_enabled': 1,
        'price': 333.33,
        'quantity': 33
    }],
    'property_values': [{
        'property_id': 200,
        'property_name': 'Color (primary)',
        'scale_id': None,
        'value': 'Orange',
        'value_id': 6
    }, {
        'property_id': 52047899002,
        'property_name': 'Color (secondary)',
        'scale_id': None,
        'value': 'Levande',
        'value_id': None
    }],
    'sku': '550'
}, {
    'offerings': [{
        'is_enabled': 1,
        'price': 33.33,
        'quantity': 33
    }],
    'property_values': [{
        'property_id': 200,
        'property_name': 'Color (primary)',
        'scale_id': None,
        'value': 'Pink',
        'value_id': 7
    }, {
        'property_id': 52047899002,
        'property_name': 'Color (secondary)',
        'scale_id': None,
        'value': 'Blue',
        'value_id': 2
    }],
    'sku': '550'
}, {
    'offerings': [{
        'is_enabled': 1,
        'price': 333.33,
        'quantity': 33
    }],
    'property_values': [{
        'property_id': 200,
        'property_name': 'Color (primary)',
        'scale_id': None,
        'value': 'Pink',
        'value_id': 7
    }, {
        'property_id': 52047899002,
        'property_name': 'Color (secondary)',
        'scale_id': None,
        'value': 'Levande',
        'value_id': None
    }],
    'sku': '550'
}, {
    'offerings': [{
        'is_enabled': 1,
        'price': 33.33,
        'quantity': 33
    }],
    'property_values': [{
        'property_id': 200,
        'property_name': 'Color (primary)',
        'scale_id': None,
        'value': 'Purple',
        'value_id': 8
    }, {
        'property_id': 52047899002,
        'property_name': 'Color (secondary)',
        'scale_id': None,
        'value': 'Blue',
        'value_id': 2
    }],
    'sku': '550'
}, {
    'offerings': [{
        'is_enabled': 1,
        'price': 333.33,
        'quantity': 33
    }],
    'property_values': [{
        'property_id': 200,
        'property_name': 'Color (primary)',
        'scale_id': None,
        'value': 'Purple',
        'value_id': 8
    }, {
        'property_id': 52047899002,
        'property_name': 'Color (secondary)',
        'scale_id': None,
        'value': 'Levande',
        'value_id': None
    }],
    'sku': '550'
}, {
    'offerings': [{
        'is_enabled': 1,
        'price': 33.33,
        'quantity': 33
    }],
    'property_values': [{
        'property_id': 200,
        'property_name': 'Color (primary)',
        'scale_id': None,
        'value': 'Rainbow',
        'value_id': 1220
    }, {
        'property_id': 52047899002,
        'property_name': 'Color (secondary)',
        'scale_id': None,
        'value': 'Blue',
        'value_id': 2
    }],
    'sku': '550'
}, {
    'offerings': [{
        'is_enabled': 1,
        'price': 333.33,
        'quantity': 33
    }],
    'property_values': [{
        'property_id': 200,
        'property_name': 'Color (primary)',
        'scale_id': None,
        'value': 'Rainbow',
        'value_id': 1220
    }, {
        'property_id': 52047899002,
        'property_name': 'Color (secondary)',
        'scale_id': None,
        'value': 'Levande',
        'value_id': None
    }],
    'sku': '550'
}, {
    'offerings': [{
        'is_enabled': 1,
        'price': 33.33,
        'quantity': 33
    }],
    'property_values': [{
        'property_id': 200,
        'property_name': 'Color (primary)',
        'scale_id': None,
        'value': 'Red',
        'value_id': 9
    }, {
        'property_id': 52047899002,
        'property_name': 'Color (secondary)',
        'scale_id': None,
        'value': 'Blue',
        'value_id': 2
    }],
    'sku': '550'
}, {
    'offerings': [{
        'is_enabled': 1,
        'price': 333.33,
        'quantity': 33
    }],
    'property_values': [{
        'property_id': 200,
        'property_name': 'Color (primary)',
        'scale_id': None,
        'value': 'Red',
        'value_id': 9
    }, {
        'property_id': 52047899002,
        'property_name': 'Color (secondary)',
        'scale_id': None,
        'value': 'Levande',
        'value_id': None
    }],
    'sku': '550'
}, {
    'offerings': [{
        'is_enabled': 1,
        'price': 33.33,
        'quantity': 33
    }],
    'property_values': [{
        'property_id': 200,
        'property_name': 'Color (primary)',
        'scale_id': None,
        'value': 'Rose gold',
        'value_id': 1217
    }, {
        'property_id': 52047899002,
        'property_name': 'Color (secondary)',
        'scale_id': None,
        'value': 'Blue',
        'value_id': 2
    }],
    'sku': '550'
}, {
    'offerings': [{
        'is_enabled': 1,
        'price': 333.33,
        'quantity': 33
    }],
    'property_values': [{
        'property_id': 200,
        'property_name': 'Color (primary)',
        'scale_id': None,
        'value': 'Rose gold',
        'value_id': 1217
    }, {
        'property_id': 52047899002,
        'property_name': 'Color (secondary)',
        'scale_id': None,
        'value': 'Levande',
        'value_id': None
    }],
    'sku': '550'
}, {
    'offerings': [{
        'is_enabled': 1,
        'price': 33.33,
        'quantity': 33
    }],
    'property_values': [{
        'property_id': 200,
        'property_name': 'Color (primary)',
        'scale_id': None,
        'value': 'Silver',
        'value_id': 1215
    }, {
        'property_id': 52047899002,
        'property_name': 'Color (secondary)',
        'scale_id': None,
        'value': 'Blue',
        'value_id': 2
    }],
    'sku': '550'
}, {
    'offerings': [{
        'is_enabled': 1,
        'price': 333.33,
        'quantity': 33
    }],
    'property_values': [{
        'property_id': 200,
        'property_name': 'Color (primary)',
        'scale_id': None,
        'value': 'Silver',
        'value_id': 1215
    }, {
        'property_id': 52047899002,
        'property_name': 'Color (secondary)',
        'scale_id': None,
        'value': 'Levande',
        'value_id': None
    }],
    'sku': '550'
}, {
    'offerings': [{
        'is_enabled': 1,
        'price': 33.33,
        'quantity': 33
    }],
    'property_values': [{
        'property_id': 200,
        'property_name': 'Color (primary)',
        'scale_id': None,
        'value': 'White',
        'value_id': 10
    }, {
        'property_id': 52047899002,
        'property_name': 'Color (secondary)',
        'scale_id': None,
        'value': 'Blue',
        'value_id': 2
    }],
    'sku': '550'
}, {
    'offerings': [{
        'is_enabled': 1,
        'price': 333.33,
        'quantity': 33
    }],
    'property_values': [{
        'property_id': 200,
        'property_name': 'Color (primary)',
        'scale_id': None,
        'value': 'White',
        'value_id': 10
    }, {
        'property_id': 52047899002,
        'property_name': 'Color (secondary)',
        'scale_id': None,
        'value': 'Levande',
        'value_id': None
    }],
    'sku': '550'
}, {
    'offerings': [{
        'is_enabled': 1,
        'price': 33.33,
        'quantity': 33
    }],
    'property_values': [{
        'property_id': 200,
        'property_name': 'Color (primary)',
        'scale_id': None,
        'value': 'Yellow',
        'value_id': 11
    }, {
        'property_id': 52047899002,
        'property_name': 'Color (secondary)',
        'scale_id': None,
        'value': 'Blue',
        'value_id': 2
    }],
    'sku': '550'
}, {
    'offerings': [{
        'is_enabled': 1,
        'price': 333.33,
        'quantity': 33
    }],
    'property_values': [{
        'property_id': 200,
        'property_name': 'Color (primary)',
        'scale_id': None,
        'value': 'Yellow',
        'value_id': 11
    }, {
        'property_id': 52047899002,
        'property_name': 'Color (secondary)',
        'scale_id': None,
        'value': 'Levande',
        'value_id': None
    }],
    'sku': '550'
}]

api_products_unpacked2 = [{
    'offerings': [{
        'is_enabled': 1,
        'price': 1,
        'quantity': 111
    }],
    'property_values': [{
        'property_id': 200,
        'property_name': 'Primary color',
        'scale_id': None,
        'value': 'Beige',
        'value_id': 1213
    }, {
        'property_id': 501,
        'property_name': 'Dimensions',
        'scale_id': 344,
        'value': '44.4',
        'value_id': None
    }],
    'sku': '111'
}, {
    'offerings': [{
        'is_enabled': 1,
        'price': 1,
        'quantity': 222
    }],
    'property_values': [{
        'property_id': 200,
        'property_name': 'Primary color',
        'scale_id': None,
        'value': 'Beige',
        'value_id': 1213
    }, {
        'property_id': 501,
        'property_name': 'Dimensions',
        'scale_id': 344,
        'value': '55.5',
        'value_id': None
    }],
    'sku': '111'
}, {
    'offerings': [{
        'is_enabled': 1,
        'price': 2,
        'quantity': 111
    }],
    'property_values': [{
        'property_id': 200,
        'property_name': 'Primary color',
        'scale_id': None,
        'value': 'Black',
        'value_id': 1
    }, {
        'property_id': 501,
        'property_name': 'Dimensions',
        'scale_id': 344,
        'value': '44.4',
        'value_id': None
    }],
    'sku': '111'
}, {
    'offerings': [{
        'is_enabled': 1,
        'price': 2,
        'quantity': 222
    }],
    'property_values': [{
        'property_id': 200,
        'property_name': 'Primary color',
        'scale_id': None,
        'value': 'Black',
        'value_id': 1
    }, {
        'property_id': 501,
        'property_name': 'Dimensions',
        'scale_id': 344,
        'value': '55.5',
        'value_id': None
    }],
    'sku': '111'
}, {
    'offerings': [{
        'is_enabled': 0,
        'price': 3,
        'quantity': 111
    }],
    'property_values': [{
        'property_id': 200,
        'property_name': 'Primary color',
        'scale_id': None,
        'value': 'Blue',
        'value_id': 2
    }, {
        'property_id': 501,
        'property_name': 'Dimensions',
        'scale_id': 344,
        'value': '44.4',
        'value_id': None
    }],
    'sku': '111'
}, {
    'offerings': [{
        'is_enabled': 0,
        'price': 3,
        'quantity': 222
    }],
    'property_values': [{
        'property_id': 200,
        'property_name': 'Primary color',
        'scale_id': None,
        'value': 'Blue',
        'value_id': 2
    }, {
        'property_id': 501,
        'property_name': 'Dimensions',
        'scale_id': 344,
        'value': '55.5',
        'value_id': None
    }],
    'sku': '111'
}, {
    'offerings': [{
        'is_enabled': 0,
        'price': 4,
        'quantity': 111
    }],
    'property_values': [{
        'property_id': 200,
        'property_name': 'Primary color',
        'scale_id': None,
        'value': 'Silver',
        'value_id': 1215
    }, {
        'property_id': 501,
        'property_name': 'Dimensions',
        'scale_id': 344,
        'value': '44.4',
        'value_id': None
    }],
    'sku': '111'
}, {
    'offerings': [{
        'is_enabled': 0,
        'price': 4,
        'quantity': 222
    }],
    'property_values': [{
        'property_id': 200,
        'property_name': 'Primary color',
        'scale_id': None,
        'value': 'Silver',
        'value_id': 1215
    }, {
        'property_id': 501,
        'property_name': 'Dimensions',
        'scale_id': 344,
        'value': '55.5',
        'value_id': None
    }],
    'sku': '111'
}, {
    'offerings': [{
        'is_enabled': 1,
        'price': 5,
        'quantity': 111
    }],
    'property_values': [{
        'property_id': 200,
        'property_name': 'Primary color',
        'scale_id': None,
        'value': 'White',
        'value_id': 10
    }, {
        'property_id': 501,
        'property_name': 'Dimensions',
        'scale_id': 344,
        'value': '44.4',
        'value_id': None
    }],
    'sku': '111'
}, {
    'offerings': [{
        'is_enabled': 1,
        'price': 5,
        'quantity': 222
    }],
    'property_values': [{
        'property_id': 200,
        'property_name': 'Primary color',
        'scale_id': None,
        'value': 'White',
        'value_id': 10
    }, {
        'property_id': 501,
        'property_name': 'Dimensions',
        'scale_id': 344,
        'value': '55.5',
        'value_id': None
    }],
    'sku': '111'
}, {
    'offerings': [{
        'is_enabled': 1,
        'price': 6,
        'quantity': 111
    }],
    'property_values': [{
        'property_id': 200,
        'property_name': 'Primary color',
        'scale_id': None,
        'value': 'Yellow',
        'value_id': 11
    }, {
        'property_id': 501,
        'property_name': 'Dimensions',
        'scale_id': 344,
        'value': '44.4',
        'value_id': None
    }],
    'sku': '111'
}, {
    'offerings': [{
        'is_enabled': 1,
        'price': 6,
        'quantity': 222
    }],
    'property_values': [{
        'property_id': 200,
        'property_name': 'Primary color',
        'scale_id': None,
        'value': 'Yellow',
        'value_id': 11
    }, {
        'property_id': 501,
        'property_name': 'Dimensions',
        'scale_id': 344,
        'value': '55.5',
        'value_id': None
    }],
    'sku': '111'
}, {
    'offerings': [{
        'is_enabled': 1,
        'price': 7,
        'quantity': 111
    }],
    'property_values': [{
        'property_id': 200,
        'property_name': 'Primary color',
        'scale_id': None,
        'value': 'Custom color 1',
        'value_id': 105393734419
    }, {
        'property_id': 501,
        'property_name': 'Dimensions',
        'scale_id': 344,
        'value': '44.4',
        'value_id': None
    }],
    'sku': '111'
}, {
    'offerings': [{
        'is_enabled': 1,
        'price': 7,
        'quantity': 222
    }],
    'property_values': [{
        'property_id': 200,
        'property_name': 'Primary color',
        'scale_id': None,
        'value': 'Custom color 1',
        'value_id': 105393734419
    }, {
        'property_id': 501,
        'property_name': 'Dimensions',
        'scale_id': 344,
        'value': '55.5',
        'value_id': None
    }],
    'sku': '111'
}, {
    'offerings': [{
        'is_enabled': 1,
        'price': 11.11,
        'quantity': 111
    }],
    'property_values': [{
        'property_id': 200,
        'property_name': 'Primary color',
        'scale_id': None,
        'value': 'New Color',
        'value_id': None
    }, {
        'property_id': 501,
        'property_name': 'Dimensions',
        'scale_id': 344,
        'value': '44.4',
        'value_id': None
    }],
    'sku': '111'
}, {
    'offerings': [{
        'is_enabled': 1,
        'price': 11.11,
        'quantity': 222
    }],
    'property_values': [{
        'property_id': 200,
        'property_name': 'Primary color',
        'scale_id': None,
        'value': 'New Color',
        'value_id': None
    }, {
        'property_id': 501,
        'property_name': 'Dimensions',
        'scale_id': 344,
        'value': '55.5',
        'value_id': None
    }],
    'sku': '111'
}]

api_products_unpacked3 = [{
    'offerings': [{
        'is_enabled': 1,
        'price': 40,
        'quantity': 4
    }],
    'property_values': [{
        'property_id': 52047899294,
        'property_name': 'Size',
        'scale_id': 25,
        'value': 'One size (plus)',
        'value_id': 1795
    }, {
        'property_id': 507,
        'property_name': 'Material',
        'scale_id': None,
        'value': 'Material 1',
        'value_id': 5561256091
    }],
    'sku': '222'
}, {
    'offerings': [{
        'is_enabled': 0,
        'price': 50,
        'quantity': 5
    }],
    'property_values': [{
        'property_id': 52047899294,
        'property_name': 'Size',
        'scale_id': 25,
        'value': 'One size (plus)',
        'value_id': 1795
    }, {
        'property_id': 507,
        'property_name': 'Material',
        'scale_id': None,
        'value': 'Material 2',
        'value_id': 5561256101
    }],
    'sku': '222'
}, {
    'offerings': [{
        'is_enabled': 1,
        'price': 70,
        'quantity': 7
    }],
    'property_values': [{
        'property_id': 52047899294,
        'property_name': 'Size',
        'scale_id': 25,
        'value': 'Custom size 1',
        'value_id': 102314214578
    }, {
        'property_id': 507,
        'property_name': 'Material',
        'scale_id': None,
        'value': 'Material 1',
        'value_id': 5561256091
    }],
    'sku': '222'
}, {
    'offerings': [{
        'is_enabled': 1,
        'price': 80,
        'quantity': 8
    }],
    'property_values': [{
        'property_id': 52047899294,
        'property_name': 'Size',
        'scale_id': 25,
        'value': 'Custom size 1',
        'value_id': 102314214578
    }, {
        'property_id': 507,
        'property_name': 'Material',
        'scale_id': None,
        'value': 'Material 2',
        'value_id': 5561256101
    }],
    'sku': '222'
}]

expected_api_calls = [{
    'PUT': '/v2/listings/100001/inventory?price_on_property=52047899002&quantity_on_property=&sku_on_property=',
    'body': {
        '_products_unpacked': api_products_unpacked1,
        'listing_id': 100001
    }
}, {
    'PUT': '/v2/listings/100002/inventory?price_on_property=200&quantity_on_property=501&sku_on_property=',
    'body': {
        '_products_unpacked': api_products_unpacked2,
        'listing_id': 100002
    }
}, {
    'PUT': '/v2/listings/100003/inventory?price_on_property=52047899294,507&quantity_on_property=52047899294,507&sku_on_property=',
    'body': {
        '_products_unpacked': api_products_unpacked3,
        'listing_id': 100003
    }
}]
