# Generated by api_requests2test_data.py

api_products_unpacked1 = [{
    'offerings': [{
        'is_enabled': 1,
        'price': 500,
        'quantity': 50
    }],
    'property_values': [],
    'sku': 'LOLO55LO'
}]

api_products_unpacked2 = [{
    'offerings': [{
        'is_enabled': 1,
        'price': 1,
        'quantity': 11
    }],
    'property_values': [{
        'property_id': 200,
        'property_name': 'Primary color',
        'scale_id': None,
        'value': 'Beige',
        'value_id': 1213
    }],
    'sku': 'LOLO111'
}, {
    'offerings': [{
        'is_enabled': 1,
        'price': 2,
        'quantity': 11
    }],
    'property_values': [{
        'property_id': 200,
        'property_name': 'Primary color',
        'scale_id': None,
        'value': 'Black',
        'value_id': 1
    }],
    'sku': 'LOLO111'
}, {
    'offerings': [{
        'is_enabled': 0,
        'price': 3,
        'quantity': 11
    }],
    'property_values': [{
        'property_id': 200,
        'property_name': 'Primary color',
        'scale_id': None,
        'value': 'Blue',
        'value_id': 2
    }],
    'sku': 'LOLO111'
}, {
    'offerings': [{
        'is_enabled': 0,
        'price': 4,
        'quantity': 11
    }],
    'property_values': [{
        'property_id': 200,
        'property_name': 'Primary color',
        'scale_id': None,
        'value': 'Silver',
        'value_id': 1215
    }],
    'sku': 'LOLO111'
}, {
    'offerings': [{
        'is_enabled': 1,
        'price': 5,
        'quantity': 11
    }],
    'property_values': [{
        'property_id': 200,
        'property_name': 'Primary color',
        'scale_id': None,
        'value': 'White',
        'value_id': 10
    }],
    'sku': 'LOLO111'
}, {
    'offerings': [{
        'is_enabled': 1,
        'price': 6,
        'quantity': 11
    }],
    'property_values': [{
        'property_id': 200,
        'property_name': 'Primary color',
        'scale_id': None,
        'value': 'Yellow',
        'value_id': 11
    }],
    'sku': 'LOLO111'
}, {
    'offerings': [{
        'is_enabled': 1,
        'price': 7,
        'quantity': 11
    }],
    'property_values': [{
        'property_id': 200,
        'property_name': 'Primary color',
        'scale_id': None,
        'value': 'Custom color 1',
        'value_id': 105393734419
    }],
    'sku': 'LOLO111'
}, {
    'offerings': [{
        'is_enabled': 1,
        'price': 8,
        'quantity': 11
    }],
    'property_values': [{
        'property_id': 200,
        'property_name': 'Primary color',
        'scale_id': None,
        'value': 'Custom color 2',
        'value_id': 50541869803
    }],
    'sku': 'LOLO111'
}]

api_products_unpacked3 = [{
    'offerings': [{
        'is_enabled': 1,
        'price': 10,
        'quantity': 1
    }],
    'property_values': [{
        'property_id': 52047899294,
        'property_name': 'Size',
        'scale_id': 25,
        'value': 'XXS',
        'value_id': 1672
    }, {
        'property_id': 507,
        'property_name': 'Material',
        'scale_id': None,
        'value': 'Material 1',
        'value_id': 5561256091
    }],
    'sku': 'LOLO2'
}, {
    'offerings': [{
        'is_enabled': 1,
        'price': 20,
        'quantity': 2
    }],
    'property_values': [{
        'property_id': 52047899294,
        'property_name': 'Size',
        'scale_id': 25,
        'value': 'XXS',
        'value_id': 1672
    }, {
        'property_id': 507,
        'property_name': 'Material',
        'scale_id': None,
        'value': 'Material 2',
        'value_id': 5561256101
    }],
    'sku': 'LOLO2'
}, {
    'offerings': [{
        'is_enabled': 1,
        'price': 30,
        'quantity': 3
    }],
    'property_values': [{
        'property_id': 52047899294,
        'property_name': 'Size',
        'scale_id': 25,
        'value': 'XXS',
        'value_id': 1672
    }, {
        'property_id': 507,
        'property_name': 'Material',
        'scale_id': None,
        'value': 'Material 3',
        'value_id': 9932879796
    }],
    'sku': 'LOLO2'
}, {
    'offerings': [{
        'is_enabled': 1,
        'price': 40,
        'quantity': 4
    }],
    'property_values': [{
        'property_id': 52047899294,
        'property_name': 'Size',
        'scale_id': 25,
        'value': 'One size (plus)',
        'value_id': 1795
    }, {
        'property_id': 507,
        'property_name': 'Material',
        'scale_id': None,
        'value': 'Material 1',
        'value_id': 5561256091
    }],
    'sku': 'LOLO2'
}, {
    'offerings': [{
        'is_enabled': 0,
        'price': 50,
        'quantity': 5
    }],
    'property_values': [{
        'property_id': 52047899294,
        'property_name': 'Size',
        'scale_id': 25,
        'value': 'One size (plus)',
        'value_id': 1795
    }, {
        'property_id': 507,
        'property_name': 'Material',
        'scale_id': None,
        'value': 'Material 2',
        'value_id': 5561256101
    }],
    'sku': 'LOLO2'
}, {
    'offerings': [{
        'is_enabled': 1,
        'price': 60,
        'quantity': 6
    }],
    'property_values': [{
        'property_id': 52047899294,
        'property_name': 'Size',
        'scale_id': 25,
        'value': 'One size (plus)',
        'value_id': 1795
    }, {
        'property_id': 507,
        'property_name': 'Material',
        'scale_id': None,
        'value': 'Material 3',
        'value_id': 9932879796
    }],
    'sku': 'LOLO2'
}, {
    'offerings': [{
        'is_enabled': 1,
        'price': 70,
        'quantity': 7
    }],
    'property_values': [{
        'property_id': 52047899294,
        'property_name': 'Size',
        'scale_id': 25,
        'value': 'Custom size 1',
        'value_id': 102314214578
    }, {
        'property_id': 507,
        'property_name': 'Material',
        'scale_id': None,
        'value': 'Material 1',
        'value_id': 5561256091
    }],
    'sku': 'LOLO2'
}, {
    'offerings': [{
        'is_enabled': 1,
        'price': 80,
        'quantity': 8
    }],
    'property_values': [{
        'property_id': 52047899294,
        'property_name': 'Size',
        'scale_id': 25,
        'value': 'Custom size 1',
        'value_id': 102314214578
    }, {
        'property_id': 507,
        'property_name': 'Material',
        'scale_id': None,
        'value': 'Material 2',
        'value_id': 5561256101
    }],
    'sku': 'LOLO2'
}, {
    'offerings': [{
        'is_enabled': 1,
        'price': 90,
        'quantity': 9
    }],
    'property_values': [{
        'property_id': 52047899294,
        'property_name': 'Size',
        'scale_id': 25,
        'value': 'Custom size 1',
        'value_id': 102314214578
    }, {
        'property_id': 507,
        'property_name': 'Material',
        'scale_id': None,
        'value': 'Material 3',
        'value_id': 9932879796
    }],
    'sku': 'LOLO2'
}]

expected_api_calls = [{
    'PUT': '/v2/listings/100001/inventory?price_on_property=&quantity_on_property=&sku_on_property=',
    'body': {
        '_products_unpacked': api_products_unpacked1,
        'listing_id': 100001
    }
}, {
    'PUT': '/v2/listings/100002/inventory?price_on_property=200&quantity_on_property=&sku_on_property=',
    'body': {
        '_products_unpacked': api_products_unpacked2,
        'listing_id': 100002
    }
}, {
    'PUT': '/v2/listings/100003/inventory?price_on_property=52047899294,507&quantity_on_property=52047899294,507&sku_on_property=',
    'body': {
        '_products_unpacked': api_products_unpacked3,
        'listing_id': 100003
    }
}]